# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
