# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='disabled',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='domain',
            name='disabled',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
