# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_id',
            new_name='marathon_app_id',
        ),
        migrations.RemoveField(
            model_name='apptenantdb',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='apptenantdb',
            name='use_tenant',
        ),
        migrations.AlterField(
            model_name='app',
            name='app_tenant_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx_routing.AppTenantDB'),
        ),
    ]
