# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0002_auto_20160120_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx_routing.App'),
        ),
    ]
