# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0002_auto_20160127_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='disabled',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='disabled',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
