# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_routing', '0003_auto_20160127_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx_routing.Group'),
        ),
    ]
