# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='0', max_length=1)),
                ('config', models.TextField(default='')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'watchers',
                'permissions': (('can_destroy', 'Can destroy watcher'), ('can_run', 'Can start, stop, restart watcher')),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Watcher'),
        ),
    ]
