# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_auto_20160114_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
