# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_auto_20160118_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcher',
            options={'permissions': (('can_destroy', 'Can destroy watcher'), ('can_run', 'Can start, stop, restart watcher'))},
        ),
    ]
