# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permmarathon',
            options={'permissions': (('can_init_app', 'Can add new, delete app'), ('can_run_app', 'Can start, stop, restart, scale app'))},
        ),
    ]
