# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:55
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermChronos',
            fields=[
            ],
            options={
                'proxy': True,
                'permissions': (('can_init_job', 'Can create, delete job'), ('can_run_job', 'Can start, stop, job')),
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
