# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronos_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permchronos',
            options={'permissions': (('can_init_job', 'Can create, delete job'), ('can_run_job', 'Can start, stop, job'))},
        ),
    ]
