# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('default', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'params',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(default='marathon', max_length=10)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.AddField(
            model_name='param',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_template.Template'),
        ),
    ]
