# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(default='marathon', max_length=20),
        ),
    ]
